export const translations = {
  en: {
    home: "Home",
    contact: "Contact",
    about: "About",
    manage: "Manage",
    usermanage:"User Manage" ,
    adminPanel: "Admin Panel",
    dashboard : "Dashboard" ,
    history : "History" ,   
    heroTitle: "Next-Gen Agile API Framework Workspace",
    heroSubtitle: "Instantly create, deploy, mock, and monitor scalable REST parameters with atomic state mutations.",
    getStarted: "Get Started Free",
    learnMore: "Learn More",
    legal: "Legal Notices",
    rights: "All rights reserved",
    theme: "Theme",
    lang: "Language",
    signOut: "Sign Out",
    actions: "Actions",
    createEndpoint: "Create Endpoint",
    updateEndpoint: "Update Endpoint",
    method: "Method",
    path: "Route Path",
    description: "Description",
    save: "Save Changes",
    cancel: "Cancel",
    loading: "Executing synchronization loop...",
    
    readOnlyNotice: "Read-Only Multi-Tenant Registry Node Overview",
    companyLabel: "Company Node",
    companyIdLabel: "Company UUID" ,

    // Auth Specific Dictionary Keys
    signInTitle: "Welcome Back",
    signInSubtitle: "Sign in to control running REST API Engine networks",
    signUpTitle: "Create Operator Account",
    signUpSubtitle: "Register session vectors directly into system tracking layers",
    emailLabel: "System Email Address",
    passwordLabel: "Secure Key Phrase",
    nameLabel: "Full Operator Name",
    btnAuthenticate: "Authenticate Identity",
    btnDeploySession: "Deploy Session Signature",
    newOperator: "New Operator?",
    provisionProfile: "Provision New Profile",
    alreadyRegistered: "Already Registered?",
    signInHere: "Sign In Here",
    successProvision: "Profile Provisioned Successfully",
    syncingDb: "Syncing credentials tokens with PostgreSQL relational clusters...",
    invalidCredentials: "Invalid credential profiles provided.",
    failedProvision: "Failed to provision runtime credentials mapping."
  },
  th: {
    home: "หน้าแรก",
    contact: "ติดต่อเรา",
    about: "เกี่ยวกับ",
    manage: "จัดการระบบ",
    usermanage:"ผู้ใช้จัดการระบบ" ,
    adminPanel: "แผงควบคุมแอดมิน",
    dashboard : "รายงาน" ,
    history : "ประวัติระเบียบ" ,
    heroTitle: "ระบบเวิร์กสเปซทดสอบ API ยุคใหม่",
    heroSubtitle: "สร้าง ปรับใช้ จำลอง และตรวจสอบพารามิเตอร์ REST API ได้อย่างรวดเร็วพร้อมระบบจัดการสถานะข้อมูล",
    getStarted: "เริ่มต้นใช้งานฟรี",
    learnMore: "เรียนรู้เพิ่มเติม",
    legal: "ข้อกำหนดทางกฎหมาย",
    rights: "สงวนลิขสิทธิ์ทั้งหมด",
    theme: "ธีมระบบ",
    lang: "เปลี่ยนภาษา",
    signOut: "ออกจากระบบ",
    actions: "เครื่องมือ",
    createEndpoint: "สร้างเอนด์พอยต์ใหม่",
    updateEndpoint: "แก้ไขเอนด์พอยต์",
    method: "เมธอด",
    path: "เส้นทางเร้าต์ (Route Path)",
    description: "รายละเอียด",
    save: "บันทึกข้อมูล",
    cancel: "ยกเลิก",
    loading: "กำลังซิงโครไนซ์ข้อมูลระบบ...",
    readOnlyNotice: "ภาพรวมพารามิเตอร์ระบบในโหมดอ่านอย่างเดียวแยกตามสิทธิ์องค์กร",
    companyLabel: "หน่วยงาน/องค์กร",
    companyIdLabel: "รหัสองค์กร UUID" ,

    // Auth Specific Dictionary Keys
    signInTitle: "ยินดีต้อนรับกลับเข้าสู่ระบบ",
    signInSubtitle: "เข้าสู่ระบบเพื่อจัดการเครือข่ายระบบ REST API Engine",
    signUpTitle: "สร้างบัญชีผู้ใช้งานผู้ดูแลระบบ",
    signUpSubtitle: "ลงทะเบียนเซสชันระบบไปยังเลเยอร์ฐานข้อมูลควบคุมโดยตรง",
    emailLabel: "ที่อยู่อีเมลของระบบ",
    passwordLabel: "รหัสผ่านความปลอดภัย",
    nameLabel: "ชื่อ-นามสกุลผู้ดูแลระบบ",
    btnAuthenticate: "ยืนยันตัวตนเข้าสู่ระบบ",
    btnDeploySession: "เปิดใช้งานสิทธิ์การเข้าถึง",
    newOperator: "ผู้ใช้งานใหม่?",
    provisionProfile: "สร้างบัญชีผู้ใช้งานใหม่ที่นี่",
    alreadyRegistered: "มีบัญชีผู้ใช้งานแล้ว?",
    signInHere: "เข้าสู่ระบบที่นี่",
    successProvision: "ลงทะเบียนบัญชีผู้ใช้งานสำเร็จแล้ว",
    syncingDb: "กำลังเชื่อมโยงโทเค็นและเซสชันระบบเข้ากับฐานข้อมูล PostgreSQL...",
    invalidCredentials: "อีเมลหรือรหัสผ่านระบบไม่ถูกต้อง กรุณาตรวจสอบอีกครั้ง",
    failedProvision: "ไม่สามารถสร้างชุดข้อมูลสิทธิ์การเข้าถึงในระบบได้"
  }
};

export type Language = "en" | "th";
export type Theme = "classic white" | "classic dark" | "classic green";
